language: node_js
node_js:
  - node # uses most recent stable node version
services:
  # - postgresql # starts up postgres
addons:
  # postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  # - psql -c 'create database "mercurycap-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: wendy-portfolio # see README
  api_key:
    secure: dSZ/icGlXILIJ7n4UhI83QQXRP5ZKuCNzRd3eZSHRQyp+mGTA9aSjF5GHcjnjenDt4EtA6vu69/Y16Wj5kzVlXCdjp5KGjG927O8shJatqDuL6e4xuUjZuuo/oXwlbsIsPEftw6Evlx9/ETcLHdAlQDt+AN1QlwDd5clq6I0gUPkn6DzoCni5VqpNtGNDh7pHT2K+vKAXPtf6kd5OvzllBMusTz1CsfR9WFOP3tN19sXCIhjR2HC0ckghaBMwgcZ0NmUwea97jX/DizmRSxSlh4cUu423oh3YVuKGYpgMVOsJVU7gtbUHnCUhEuPJUaoZ6EfWZ7qQp5LKIE4PjEnvnjr5WT/1z/vS3NRoASvNTgzQk7IHen/WMvDIY/lRBifyDvc6xkJinNVuVr6RG9FB8KXbGPIJQXeMIGp1KfoRLADY6f5dSv+rQvipvpZXTegtyHxpTfMte309Gm0jVdnRiDPzcFZ5pOK0ZlMdYukIYZ7X5uT0wJpFA9U8C59C7MxogWEUBiGDrpfQOJbn+1FbbKmGor+iTncc9nvl3U5yxb+vh8zt/A7KpzuXdB8pl6UQjCUsSNi17u3uKIHOj0srLx2EAYJtKubclqHMAZopnIdMmsUOHZRtco14hzcw7pB/dL/whIMIcRYTYChL/SDLxeg4j57zQ1Hap56cyxt8w0= # see README
