language: node_js
node_js:
  - node # uses most recent stable node version
services:
  # - postgresql # starts up postgres
addons:
  # postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  # - psql -c 'create database "mercurycap-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: wendy-portfolio # see README
  api_key:
    secure: h5husPcqBnFk/tjXWfFHkKPEgSrYN+PioW8vZ1mBjy1y8MBHt30cDbmXM1MyePhUCRqmyFcEP//robin4KwNCQ8SlIlnLSL7DppVM/YvJh2urUs7QUKC794UzNIdaVs57TeeMyRVyetcBtcG8w47oHlHn35zG30AhXwGtzlSrNq7n/11sn5tDPHp5XaOx/Dm3lxTYa1dlOIWL9BP3YoVavW9HlVlfXyMEsFRFExjX0YWSU5QEut06CbDcpbE9tx+/i3f+XIkGRJyEC1E44ei1h4rxo1aGkwheC7u0nPCZe6JCe6OYkBs/IRYX0TxVlurwlOaqu+PXjK2duuI+8QfN+RqkTYRTxJgVLxYcYWoSFz2nWVXs1s3HXiouvdBJ/0ElZFCcql2UZ0B7Pcy3qSuxtfeVeMtBGU0CyvAl4rLK+gJA4CbU9JmyWAaM+esCdd8TW6rOBjzI8ss3udSbPWHcwVIDWIM7eMf4Kvtp/vj7WE3nF7B+1mn3J6GJKMKEdjSXfyllc71aGjmCohCDf5BRNFRmrH4exCJztZUBNEgEawkZ1AHxXT/7s7LhJo93MQdQSnawStZyas8k1wmPRXScWlQKOtCmd0ZFaqChUsVzj8FFxooANAVShzpf0vM5QagtrTfYyDms44q7WkXodrJU3YF9RjDsO51OXPvQMMLITE= # see README
